# Generated by Django 5.1.1 on 2024-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
