# Generated by Django 5.1.1 on 2024-10-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
