# Generated by Django 5.1.1 on 2024-10-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_purchase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='datetime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
